routes/web.php
<?php

use App\Models\Student;
use App\Models\Teacher;
use App\Models\AcademicYear;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SkillController;
use App\Http\Controllers\SchoolController;
use Psr\Http\Message\ServerRequestInterface;
use App\Http\Controllers\Admin\ExamController;
use App\Http\Controllers\Admin\RoomController;
use App\Http\Controllers\Admin\ClassController;
use App\Http\Controllers\Admin\SectionController;
use App\Http\Controllers\Admin\StudentController;
use App\Http\Controllers\Admin\SubjectController;
use App\Http\Controllers\Admin\TeacherController;
use App\Http\Controllers\Admin\AttendanceController;
use App\Http\Controllers\Admin\AcademicYearController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/result_by_student',function(){
    // return view('backend.reports.result_by_student');
});

Route::get('/test', function () {
//  getSchool(1,'active');
    return view('backend.students.import');

    // return human_file_size(1024*1024);
    // return getSchool(1);
});



Route::get('lang/{locale}', function ($locale) {
    App::setLocale($locale);
    session()->put('locale', $locale);
    return redirect()->back();
});


Route::get('/', [App\Http\Controllers\FrontPageController::class, 'index'])->name('index');
Route::get('/contact', [App\Http\Controllers\FrontPageController::class, 'contact'])->name('contact');
Route::get('/about', [App\Http\Controllers\FrontPageController::class, 'about'])->name('about');
Route::get('/student-absent', [App\Http\Controllers\FrontPageController::class, 'student_absent'])->name('student.absent');
Route::get('/student-top5/{class}', [App\Http\Controllers\FrontPageController::class, 'student_top5'])->name('student.top5');
Route::get('/student-top5_print/{class}', [App\Http\Controllers\FrontPageController::class, 'student_top5_print'])->name('student.top5.print');
Route::get('/teachers', [App\Http\Controllers\FrontPageController::class, 'teachers'])->name('teachers');
Route::get('/result-exam/{class}', [App\Http\Controllers\FrontPageController::class, 'result_exam'])->name('result.exam');
Route::get('/student_register', [App\Http\Controllers\FrontPageController::class, 'student_register'])->name('student_register');




Route::get('/get_top_5_monthly',[App\Http\Controllers\Admin\GeneralController::class,'get_top_5_monthly'])->name('get_top_5_monthly');

// Filter Scores Table
Route::get('/filterScores',[App\Http\Controllers\Admin\GeneralController::class,'filterScores'])->name('filterScores');
// filterScoresClassID
Route::get('/filterScoresClassID',[App\Http\Controllers\Admin\GeneralController::class,'filterScoresClassID'])->name('filterScoresClassID');

// Route::post('get_classes', [App\Http\Controllers\Admin\ClassController::class,'get_classes'])->name('get_classes');


// Route::match(['get','post'],'exams',[App\Http\Controllers\Admin\ExamController::class,'index'])->name('exams.create');



Auth::routes();

// Admin Route
Route::group(['prefix' =>'admin','middleware'=>['web','auth']], function () {
// Route::prefix('admin')->group(function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('admin.home');

    Route::resources([
        'settings/schools' => SchoolController::class,
        'settings/skills' => SkillController::class,
        'settings/subjects' => SubjectController::class,
        'settings/sections' => SectionController::class,
        'settings/rooms' => RoomController::class,
        'settings/classes' => ClassController::class,
        'settings/credit_score' => SkillController::class,

        'teachers' => TeacherController::class,
        'students' => StudentController::class,
        // 'exams' => ExamController::class,
        'exam_details' => TeacherController::class,
        // 'attendances' => AttendanceController::class,
        'attendance_teachers' => TeacherController::class,
        // 'attendance_students' => AttendanceController::class,
        'settings/academic_years' => AcademicYearController::class,

    ]);

    // Student
    Route::get('students/import_view',[App\Http\Controllers\Admin\StudentController::class, 'ImportView'])->name('students.import_view');
    Route::post('students/import',[App\Http\Controllers\Admin\StudentController::class, 'import'])->name('students.import');


    Route::post('students/filter',[App\Http\Controllers\Admin\StudentController::class, 'filter'])->name('students.filter');

    //Attendance Controller
			Route::match(['get','post'],'attendance_students',[App\Http\Controllers\Admin\AttendanceController::class,'index'])->name('student_attendance.create');
			Route::post('student_attendance/save', [App\Http\Controllers\Admin\AttendanceController::class,'student_attendance_save'])->name('student_attendance.save');
			Route::post('classes/get_classes', [App\Http\Controllers\Admin\ClassController::class,'get_classes'])->name('classes.get_classes');

    // Exams
    Route::match(['get','post'],'exams',[App\Http\Controllers\Admin\ExamController::class,'index'])->name('exams.create');
    // student_score_save
    Route::post('student_score/save', [App\Http\Controllers\Admin\ExamController::class,'student_score_save'])->name('student_score.save');



    // Reports
    Route::get('score/monthly_top_five',[App\Http\Controllers\Admin\GeneralController::class, 'monthly_top_five'])->name('admin.monthly_top_five');
    Route::get('score/yearly_top_five',[App\Http\Controllers\Admin\GeneralController::class, 'yearly_top_five'])->name('admin.yearly_top_five');
    Route::get('score/result_by_student',[App\Http\Controllers\Admin\GeneralController::class, 'result_by_student'])->name('admin.result_by_student');

    Route::match(['get','post'],'score/student_atten_report',[App\Http\Controllers\Admin\AttendanceController::class,'student_atten_report'])->name('admin.student_attendance.student_atten_report');



    Route::match(['get','post'],'score/generateMonltyScoreReport',[App\Http\Controllers\Admin\GeneralController::class,'generateMonltyScoreReport'])->name('admin.generateMonltyScoreReport');
    Route::post('score/generateMonltyScoreReportSave', [App\Http\Controllers\Admin\GeneralController::class,'generateMonltyScoreReportSave'])->name('admin.generateMonltyScoreReportSave');

    // student_score_by_class
    Route::match(['get','post'],'score/student_score_by_class',[App\Http\Controllers\Admin\GeneralController::class,'student_score_by_class'])->name('admin.student_score_by_class');

    // student_report_by_class
    Route::match(['get','post'],'score/student_report_by_class',[App\Http\Controllers\Admin\GeneralController::class,'student_report_by_class'])->name('admin.student_report_by_class');




    // Route::resource('schools', SchoolController::class)->only([
    //     'index', 'show'
    // ]);
});

// Manager
Route::group(['prefix' =>'manager','middleware'=>['web','auth']], function () {
// Route::prefix('manager')->group(function(){

    Route::get('import_view',[App\Http\Controllers\Admin\StudentController::class, 'ImportView'])->name('students.import_view');
    Route::get('export', [App\Http\Controllers\Admin\StudentController::class, 'export'])->name('students.export');
    Route::post('import', [App\Http\Controllers\Admin\StudentController::class, 'import'])->name('students.import');

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('manager.home');



});

// Teacher
Route::group(['prefix' =>'teacher','middleware'=>['web','auth']], function () {
// Route::prefix('teacher')->group(function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('teacher.home');
});

resources/views/backend/yearly_top_five/add.blade.php
@extends('layouts.admin')

@section('content')

    <section class="content pt-2">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title text-center">{{trans('controls.forms.Add New')}}</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form>
                  <div class="card-body">

                    <div class="form-group">
                      <label for="name">{{trans('controls.schools.name')}}</label>
                      <input type="text" class="form-control" id="name" placeholder="បឋម.ស្វាយធំ">
                    </div>

                    <div class="form-group">
                        <label for="name">{{trans('controls.schools.phone')}}</label>
                        <input type="text" class="form-control" id="name" placeholder="092771244">
                    </div>

                    <div class="form-group">
                        <label for="name">{{trans('controls.schools.email')}}</label>
                        <input type="email" class="form-control" id="name" placeholder="yourschool@gmail.com">
                    </div>

                    <div class="form-group">
                        <label for="name">{{trans('controls.schools.city')}}</label>
                        <input type="text" class="form-control" id="name" placeholder="Siem Reap">
                    </div>
                    <div class="form-group">
                        <label for="name">{{trans('controls.schools.address')}}</label>
                        <input type="text" class="form-control" id="name" placeholder="ភូមិ ឃុំ ស្រុក">
                    </div>

                  </div>
                  <!-- /.card-body -->

                  <div class="card-footer float-right">
                    <button type="submit" class="btn btn-primary mr-3">{{trans('controls.save')}}</button>
                    <button type="submit" class="btn btn-danger">{{trans('controls.cancel')}}</button>
                  </div>
                </form>
              </div>
              <!-- /.card -->


            </div>
            <!--/.col (left) -->
            <!-- right column -->
            <div class="col-md-6">
              <!-- Form Element sizes -->
              <div class="card card-success">
                <div class="card-header">
                  <h3 class="card-title">ពត៌មាន​នាយក</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="name">{{trans('controls.schools.director_name')}}</label>
                        <input type="text" class="form-control" id="name" placeholder="សេង ស៊ង់">
                    </div>

                    <div class="form-group">
                        <label for="name">{{trans('controls.schools.email')}}</label>
                        <input type="text" class="form-control" id="name" placeholder="សេង ស៊ង់">
                    </div>

                    <div class="form-group">
                        <label for="name">{{trans('controls.schools.phone')}}</label>
                        <input type="text" class="form-control" id="name" placeholder="សេង ស៊ង់">
                    </div>
                    <div class="form-group">
                        <label for="name">{{trans('controls.schools.gender')}}</label>
                        <input type="text" class="form-control" id="name" placeholder="M or F">
                    </div>
                    <div class="form-group">
                        <label for="name">{{trans('controls.schools.bod')}}</label>
                        <input type="text" class="form-control" id="name" placeholder="1983-04-18">
                    </div>

                    <div class="form-group">
                        <label for="name">{{trans('controls.schools.pob')}}</label>
                        <input type="text" class="form-control" id="name" placeholder="គោករុន​ មុខប៉ែន ពួក សៀមរាប">
                    </div>

                    <div class="form-group">
                        <label for="name">រូបថតកាត</label>
                        <input type="text" class="form-control" id="name" placeholder="សេង ស៊ង់">
                    </div>


                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->



            </div>
            <!--/.col (right) -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </section>

@endsection

resources/views/backend/yearly_top_five/edit.blade.php
<div class="container pt-3 px-4">
    <form action="{{ route('brands.store') }}" method="post">
        @csrf

        <div class="row">
            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <input type="text" id="b_name" class="form-control" name="name" />
                    <label class="form-label" for="b_name">{{trans('controls.b_name')}}</label>
                </div>
            </div>

            <div class="col-md-12 mb-2 gx-2">
                <div class="form-outline form-group">
                    <textarea id="description" class="form-control" cols="30"  rows="5" name="description"></textarea>
                    {{-- {{!! Form::textarea($name, $value, [$options]) !!}} --}}
                    {{-- <input type="texteara" id="description" class="form-control" name="description" /> --}}

                    <label class="form-label" for="description">{{ __('controls.description')}}</label>
                </div>
            </div>
        </div>



    </form>
</div>

resources/views/backend/yearly_top_five/home.blade.php
@extends('layouts.admin')

@push('custom_css')

<!-- DataTables -->
<link rel="stylesheet" href="{{asset('themes')}}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{asset('themes')}}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="{{asset('themes')}}/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

 <!-- daterange picker -->
 <link rel="stylesheet" href="{{asset('themes')}}/plugins/daterangepicker/daterangepicker.css">
@endpush


@section('content')

     <!--Section: Sales Performance KPIs-->
     <section class="content pt-2">
        <div class="card">
          <div class="card-header text-left py-3" style="height: 9vh;">
            <h5 class="mb-0 text-left">

                <strong>{{trans('controls.schools.list')}}</strong>

                <span >
                    <a href="{{route('schools.create')}}"
                    class="btn btn-primary btn-sm float-right"

                    data-toggle="modal-ajax"
                    {{-- data-toggle="modal" --}}
                    {{-- data-modal-size="modal-lg" --}}
                    data-modal-size="modal-xl"
                    {{-- modal-xl --}}
                    {{-- data-mdb-toggle="modal" --}}
                    {{-- data-target="#exampleModal" --}}
                    data-target="#openModal"
                    >
                    <i class="fas fa-plus-circle"></i> {{trans('controls.forms.Add')}}</a>
                </span>
            </h5>
          </div>


          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover text-nowrap" id="DataTableList">
                <thead>
                  <tr>
                    <th scope="col" style="width: 40px !important;">{{trans('controls.forms.ID')}}</th>
                    <th scope="col">{{__('controls.schools.name')}}</th>
                    <th scope="col">{{__('controls.schools.address')}}</th>
                    <th scope="col">{{__('controls.schools.director_name')}}</th>
                    {{-- <th scope="col">Gender</th> --}}
                    <th scope="col">{{__('controls.forms.Created By')}}</th>
                    <th scope="col">{{__('controls.forms.Action')}}</th>
                  </tr>
                </thead>
                <tbody>

                    @foreach ($schools as $row)
                        @include('backend.skills.rows')
                    @endforeach


                </tbody>
              </table>
            </div>
          </div>


        </div>
     </section>
      <!--Section: Sales Performance KPIs-->

{{-- @endif --}}


@endsection


@push('custom_js')

<!-- DataTables  & Plugins -->
<script src="{{asset('themes')}}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{asset('themes')}}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{asset('themes')}}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{asset('themes')}}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="{{asset('themes')}}/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="{{asset('themes')}}/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="{{asset('themes')}}/plugins/jszip/jszip.min.js"></script>
<script src="{{asset('themes')}}/plugins/pdfmake/pdfmake.min.js"></script>
<script src="{{asset('themes')}}/plugins/pdfmake/vfs_fonts.js"></script>
<script src="{{asset('themes')}}/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="{{asset('themes')}}/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="{{asset('themes')}}/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>


<!-- date-range-picker -->
<script src="{{asset('themes')}}/plugins/daterangepicker/daterangepicker.js"></script>

<script src="{{asset('dropzone/dist/dropzone.js')}}"></script>



<script>

    $(document).ready(function() {
           $('#DataTableList').DataTable({
            ordering:true,
            processing: false,
            // serverSide: true,
            "order": [[ 4, "asc" ]],
            language : $('html').attr('lang') != 'en' ? window.datatableI18n[$('html').attr('lang')] : null,
        });
    } );

        $(document).on('click',`[data-toggle="modal-ajax"]`,function(ev){
                    ev.preventDefault();
                    var url = $(this).attr('href');
                    var modalSize = $(this).data('modal-size');
                    var title = $(this).text();
                    // var target = $(this).data('mdb-target');
                    var target = $(this).data('target');


                    $.get(url).done((res)=>{
                        var $modal = $(target);
                        $modal.find('.modal-title').text(title);
                        $modal.find('.modal-dialog').addClass(modalSize);
                        $modal.find('.modal-body').html(res);

                      //  $.getScript(`${location.origin }/themes/js/mdb.min.js`).done();

                        $modal.modal('show');

                        $modal.find('button#btn-submit').unbind().click(function(ev){
                            ev.preventDefault();

                            var $form = $modal.find('form');
                            var formData = new FormData($form[0]);
                            $.ajax({
                                url : $form.attr('action'),
                                method : 'post',
                                data : formData,
                                processData : false,
                                contentType : false,
                                success : (res)=>{
                                    if(res.status){

                                        Swal.fire({
                                            position: 'top-end',
                                            icon: 'success',
                                            title: '{{__('controls.Your data has been saved or updated!')}}',
                                            showConfirmButton: false,
                                            timer: 1500
                                        });


                                        if($(this).data('allow-close')){
                                            $modal.find(`[data-dismiss="modal"]`).click();
                                        }
                                        if ( url.match('edit')) {
                                            $('#DataTableList').find(`tr[data-id="${res.data.id}"]`).html($(res.dom).html());
                                        }else{
                                            $('#DataTableList').find('tbody').prepend(res.dom);
                                        }


                                        $form[0].reset();
                                    }

                                },
                            })

                        });
                        $modal.find(`[data-dismiss="modal"]`).click(function(ev){
                            ev.preventDefault();
                            $modal.modal('hide');
                            $modal.find('.modal-body').html("");

                        });


                    });

                });

</script>


<script type="text/javascript">
    $(document).on('submit',`[data-toggle="formDelete"]`,function(ev){
        ev.preventDefault();
        $.ajax({
            url : $(this).attr('action'),
            method : 'post',
            data : new FormData(ev.target),
            processData : false,
            contentType : false,
            success : (res)=>{
                if(res.status){
                    Swal.fire(
                        '{{trans('controls.delete')}}!',
                        '{{trans('controls.Your file has been deleted.')}}',
                        'success'
                    );
                    $(this).parents("tr").remove();
                }else{
                    Swal.fire(
                        '{{trans('controls.delete')}}!',
                        '{{trans('controls.delete_message_can_not')}}',
                        'error'
                    )
                }
            }

        })
    });

    function deleteItem(id){
      Swal.fire({
        title: "{{trans('controls.Are you sure?')}}",
        text: "{{trans('controls.You will not be able to delete this!')}}",
        icon: 'warning',
        showCancelButton: true,

        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        cancelButtonText :"{{trans('controls.cancel')}}",
        confirmButtonText:  "{{trans('controls.Yes, delete it!')}}"
      }).then((result) => {
        if (result.value) {
          $('#frmDeleteItem-'+id).submit();

        }
      })
    }
</script>

@endpush

resources/views/backend/yearly_top_five/rows.blade.php
<tr data-id="{{ $row->id}}">
    <th scope="row" style="width: 40px !important;">{{$row->id}}</th>
    <td>
        {{$row->name}}
        <br>
        <span class="text-success">
            {{-- <i class="fas fa-calculator me-1"></i> <span> {{ $row->products()->count() }} {{trans('controls.Products')}}</span> --}}
        </span>

    </td>
    <td>
        {{$row->address}}
    </td>

    <td>
        {{$row->director_name}}
    </td>

    <td>
        {{-- <i class="fas fa-user me-1"></i><span> {{$row->users($row->created_by)->last_name}}</span> --}}
        <br>
        <span class="text-success">
            {{-- <i class="fas fa-clock me-1"></i><span> {{ session()->get('locale')=='kh'?KhmerDateTime\KhmerDateTime::parse($row->created_at)->fromNow():$row->created_at->diffForHumans() }}</span> --}}
        </span>

    </td>


    <td>
        <a class="btn btn-primary  edit_button btn-sm" href="{{route('schools.show',$row)}}"
                data-toggle="modal-ajax"
                {{-- data-modal-size="modal-lg" --}}
                data-modal-size="modal-xl"
                {{-- data-mdb-toggle="modal" --}}
                data-target="#openModal"
        ><i class="fa fa-eye left"></i> {{ trans('controls.forms.Show')}}</a>

        <a class="btn btn-primary  edit_button btn-sm" href="{{route('schools.edit',$row)}}"
                data-toggle="modal-ajax"
                {{-- data-modal-size="modal-lg" --}}
                data-modal-size="modal-xl"
                {{-- data-mdb-toggle="modal" --}}
                data-target="#openModal"
        ><i class="fa fa-edit left"></i> {{ trans('controls.forms.Edit')}}</a>


        <a href="javascript:deleteItem({{ $row->id }})"​​ class="btn btn-danger delete_button btn-sm"><i class="fa fa-trash-alt left"></i> {{ trans('controls.forms.Delete')}}</a>


        <form data-toggle="formDelete"  id="frmDeleteItem-{{ $row->id }}" style="display: none" action="{{ route('schools.destroy',$row->id) }}" role="form" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
        </form>

    </td>
</tr>