routes/web.php
<?php

use App\Models\Student;
use App\Models\Teacher;
use App\Models\AcademicYear;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SkillController;
use App\Http\Controllers\SchoolController;
use Psr\Http\Message\ServerRequestInterface;
use App\Http\Controllers\Admin\ExamController;
use App\Http\Controllers\Admin\RoomController;
use App\Http\Controllers\Admin\ClassController;
use App\Http\Controllers\Admin\SectionController;
use App\Http\Controllers\Admin\StudentController;
use App\Http\Controllers\Admin\SubjectController;
use App\Http\Controllers\Admin\TeacherController;
use App\Http\Controllers\Admin\AttendanceController;
use App\Http\Controllers\Admin\AcademicYearController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/result_by_student',function(){
    // return view('backend.reports.result_by_student');
});

Route::get('/test', function () {
//  getSchool(1,'active');
    return view('backend.students.import');

    // return human_file_size(1024*1024);
    // return getSchool(1);
});



Route::get('lang/{locale}', function ($locale) {
    App::setLocale($locale);
    session()->put('locale', $locale);
    return redirect()->back();
});


Route::get('/', [App\Http\Controllers\FrontPageController::class, 'index'])->name('index');
Route::get('/contact', [App\Http\Controllers\FrontPageController::class, 'contact'])->name('contact');
Route::get('/about', [App\Http\Controllers\FrontPageController::class, 'about'])->name('about');
Route::get('/student-absent', [App\Http\Controllers\FrontPageController::class, 'student_absent'])->name('student.absent');
Route::get('/student-top5/{class}', [App\Http\Controllers\FrontPageController::class, 'student_top5'])->name('student.top5');
Route::get('/student-top5_print/{class}', [App\Http\Controllers\FrontPageController::class, 'student_top5_print'])->name('student.top5.print');
Route::get('/teachers', [App\Http\Controllers\FrontPageController::class, 'teachers'])->name('teachers');
Route::get('/result-exam/{class}', [App\Http\Controllers\FrontPageController::class, 'result_exam'])->name('result.exam');
Route::get('/student_register', [App\Http\Controllers\FrontPageController::class, 'student_register'])->name('student_register');




Route::get('/get_top_5_monthly',[App\Http\Controllers\Admin\GeneralController::class,'get_top_5_monthly'])->name('get_top_5_monthly');

// Filter Scores Table
Route::get('/filterScores',[App\Http\Controllers\Admin\GeneralController::class,'filterScores'])->name('filterScores');
// filterScoresClassID
Route::get('/filterScoresClassID',[App\Http\Controllers\Admin\GeneralController::class,'filterScoresClassID'])->name('filterScoresClassID');

// Route::post('get_classes', [App\Http\Controllers\Admin\ClassController::class,'get_classes'])->name('get_classes');


// Route::match(['get','post'],'exams',[App\Http\Controllers\Admin\ExamController::class,'index'])->name('exams.create');



Auth::routes();

// Admin Route
Route::group(['prefix' =>'admin','middleware'=>['web','auth']], function () {
// Route::prefix('admin')->group(function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('admin.home');

    Route::resources([
        'settings/schools' => SchoolController::class,
        'settings/skills' => SkillController::class,
        'settings/subjects' => SubjectController::class,
        'settings/sections' => SectionController::class,
        'settings/rooms' => RoomController::class,
        'settings/classes' => ClassController::class,
        'settings/credit_score' => SkillController::class,

        'teachers' => TeacherController::class,
        'students' => StudentController::class,
        // 'exams' => ExamController::class,
        'exam_details' => TeacherController::class,
        // 'attendances' => AttendanceController::class,
        'attendance_teachers' => TeacherController::class,
        // 'attendance_students' => AttendanceController::class,
        'settings/academic_years' => AcademicYearController::class,

    ]);

    // Student
    Route::get('students/import_view',[App\Http\Controllers\Admin\StudentController::class, 'ImportView'])->name('students.import_view');
    Route::post('students/import',[App\Http\Controllers\Admin\StudentController::class, 'import'])->name('students.import');


    Route::post('students/filter',[App\Http\Controllers\Admin\StudentController::class, 'filter'])->name('students.filter');

    //Attendance Controller
			Route::match(['get','post'],'attendance_students',[App\Http\Controllers\Admin\AttendanceController::class,'index'])->name('student_attendance.create');
			Route::post('student_attendance/save', [App\Http\Controllers\Admin\AttendanceController::class,'student_attendance_save'])->name('student_attendance.save');
			Route::post('classes/get_classes', [App\Http\Controllers\Admin\ClassController::class,'get_classes'])->name('classes.get_classes');

    // Exams
    Route::match(['get','post'],'exams',[App\Http\Controllers\Admin\ExamController::class,'index'])->name('exams.create');
    // student_score_save
    Route::post('student_score/save', [App\Http\Controllers\Admin\ExamController::class,'student_score_save'])->name('student_score.save');



    // Reports
    Route::get('score/monthly_top_five',[App\Http\Controllers\Admin\GeneralController::class, 'monthly_top_five'])->name('admin.monthly_top_five');
    Route::get('score/yearly_top_five',[App\Http\Controllers\Admin\GeneralController::class, 'yearly_top_five'])->name('admin.yearly_top_five');
    Route::get('score/result_by_student',[App\Http\Controllers\Admin\GeneralController::class, 'result_by_student'])->name('admin.result_by_student');

    Route::match(['get','post'],'score/student_atten_report',[App\Http\Controllers\Admin\AttendanceController::class,'student_atten_report'])->name('admin.student_attendance.student_atten_report');



    Route::match(['get','post'],'score/generateMonltyScoreReport',[App\Http\Controllers\Admin\GeneralController::class,'generateMonltyScoreReport'])->name('admin.generateMonltyScoreReport');
    Route::post('score/generateMonltyScoreReportSave', [App\Http\Controllers\Admin\GeneralController::class,'generateMonltyScoreReportSave'])->name('admin.generateMonltyScoreReportSave');

    // student_score_by_class
    Route::match(['get','post'],'score/student_score_by_class',[App\Http\Controllers\Admin\GeneralController::class,'student_score_by_class'])->name('admin.student_score_by_class');

    // student_report_by_class
    Route::match(['get','post'],'score/student_report_by_class',[App\Http\Controllers\Admin\GeneralController::class,'student_report_by_class'])->name('admin.student_report_by_class');




    // Route::resource('schools', SchoolController::class)->only([
    //     'index', 'show'
    // ]);
});

// Manager
Route::group(['prefix' =>'manager','middleware'=>['web','auth']], function () {
// Route::prefix('manager')->group(function(){

    Route::get('import_view',[App\Http\Controllers\Admin\StudentController::class, 'ImportView'])->name('students.import_view');
    Route::get('export', [App\Http\Controllers\Admin\StudentController::class, 'export'])->name('students.export');
    Route::post('import', [App\Http\Controllers\Admin\StudentController::class, 'import'])->name('students.import');

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('manager.home');



});

// Teacher
Route::group(['prefix' =>'teacher','middleware'=>['web','auth']], function () {
// Route::prefix('teacher')->group(function(){
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('teacher.home');
});

resources/views/backend/class_result_report/modal/add.blade.php
<div class="container pt-1">
    <form action="{{ route('schools.store') }}" method="post" enctype="multipart/form-data">
        @csrf

        <div class="row">
            <div class="col-md-6 bg-info pt-3">

                  <div class="form-group row">
                        <label for="lable_s_name" class="col-sm-3 col-form-label">{{trans('controls.schools.name')}}</label>
                        <div class="col-sm-9">
                            <input type="text" name="school_name"  class="form-control" id="lable_s_name" placeholder="បឋម.ស្វាយធំ">
                        </div>
                    </div>


                    <div class="form-group row">
                        <label for="lable_s_phone" class="col-sm-3 col-form-label">{{trans('controls.schools.phone')}}</label>
                        <div class="col-sm-9">
                            <input type="text" name="school_phone"  class="form-control" id="lable_s_phone" placeholder="092771244">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="lable_s_email" class="col-sm-3 col-form-label">{{trans('controls.schools.email')}}</label>
                        <div class="col-sm-9">
                            <input type="email" name="school_email"  class="form-control" id="lable_s_email" placeholder="yourschool@gmail.com">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="lable_s_city" class="col-sm-3 col-form-label">{{trans('controls.schools.city')}}</label>
                        <div class="col-sm-9">
                            <input type="text" name="school_city"  class="form-control" id="lable_s_city" placeholder="Siem Reap">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="lable_s_address" class="col-sm-3 col-form-label">{{trans('controls.schools.address')}}</label>
                        <div class="col-sm-9">
                            <input type="text" name="school_address"  class="form-control" id="lable_s_address" placeholder="ភូមិ ឃុំ ស្រុក">
                        </div>
                    </div>



            </div>


            <div class="col-md-6 bg-success pt-3">
                {{-- Director --}}
                <div class="form-group row">
                    <label for="lable_name" class="col-sm-3 col-form-label">{{trans('controls.schools.director_name')}}</label>
                    <div class="col-sm-9">
                        <input type="text" name="teacher_name" class="form-control" id="lable_name" placeholder="នាមត្រកូល នាមខ្លួន - FirstName LastName">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_gender" class="col-sm-3 col-form-label">{{trans('controls.teachers.gender')}}</label>
                    <div class="col-sm-9">
                        <select class="custom-select">
                            <option>{{trans('controls.forms.Please Select')}}</option>
                            <option  value="m">{{trans('controls.forms.Male')}}</option>
                            <option  value="f">{{trans('controls.forms.Female')}}</option>
                          </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_dob" class="col-sm-3 col-form-label">{{trans('controls.teachers.dob')}}</label>
                    <div class="col-sm-9">
                        <div class="input-group date" id="lable_dob" data-target-input="nearest">
                            <input type="date" name="teacher_dob"  id="lable_dob" class="form-control">
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_pob" class="col-sm-3 col-form-label">{{trans('controls.teachers.pob')}}</label>
                    <div class="col-sm-9">
                        <input type="text" name="teacher_pob"  class="form-control" id="lable_pob" placeholder="គោករុន មុខប៉ែន ពួក សៀមរាប">
                    </div>
                </div>

                 <div class="form-group row">
                    <label for="lable_t_address" class="col-sm-3 col-form-label">{{trans('controls.teachers.address')}}</label>
                    <div class="col-sm-9">
                        <input type="text"  name="teacher_address" class="form-control" id="lable_t_address" placeholder="គោករុន មុខប៉ែន ពួក សៀមរាប">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_t_city" class="col-sm-3 col-form-label">{{trans('controls.schools.city')}}</label>
                    <div class="col-sm-9">
                        <input type="text" name="teacher_city"  class="form-control" id="lable_t_city" placeholder="សៀមរាប">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_t_email" class="col-sm-3 col-form-label">{{trans('controls.schools.email')}}</label>
                    <div class="col-sm-9">
                        <input type="text" name="teacher_email"  class="form-control" id="lable_t_email" placeholder="teacher_name@gmail.com">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_t_profile" class="col-sm-3 col-form-label">{{trans('controls.teachers.profile')}}</label>
                    <div class="col-sm-9">
                        <div class="custom-file">
                            <input type="file">
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </form>
</div>

resources/views/backend/class_result_report/modal/edit.blade.php
<div class="container pt-1">
    <form action="{{ route('schools.update',$school) }}" method="post">
        @csrf
        {{ method_field('PUT') }}

        <div class="row">
            <div class="col-md-6 bg-info pt-3">

                  <div class="form-group row">
                        <label for="lable_s_name" class="col-sm-3 col-form-label">{{trans('controls.schools.name')}}</label>
                        <div class="col-sm-9">
                            <input type="text" name="school_name" value="{{$school->name}}" class="form-control" id="lable_s_name" placeholder="បឋម.ស្វាយធំ">
                        </div>
                    </div>


                    <div class="form-group row">
                        <label for="lable_s_phone" class="col-sm-3 col-form-label">{{trans('controls.schools.phone')}}</label>
                        <div class="col-sm-9">
                            <input type="text" name="school_phone" value="{{$school->phone}}" class="form-control" id="lable_s_phone" placeholder="092771244">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="lable_s_email" class="col-sm-3 col-form-label">{{trans('controls.schools.email')}}</label>
                        <div class="col-sm-9">
                            <input type="email" name="school_email" value="{{$school->email}}" class="form-control" id="lable_s_email" placeholder="yourschool@gmail.com">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="lable_s_city" class="col-sm-3 col-form-label">{{trans('controls.schools.city')}}</label>
                        <div class="col-sm-9">
                            <input type="text" name="school_city" value="{{$school->city}}" class="form-control" id="lable_s_city" placeholder="Siem Reap">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="lable_s_address" class="col-sm-3 col-form-label">{{trans('controls.schools.address')}}</label>
                        <div class="col-sm-9">
                            <input type="text" name="school_address" value="{{$school->address}}"  class="form-control" id="lable_s_address" placeholder="ភូមិ ឃុំ ស្រុក">
                        </div>
                    </div>



            </div>


            <div class="col-md-6 bg-success pt-3">
                {{-- Director --}}
                <div class="form-group row">
                    <label for="lable_name" class="col-sm-3 col-form-label">{{trans('controls.schools.director_name')}}</label>
                    <div class="col-sm-9">
                        <input type="text" name="teacher_name" value="{{$teacher->name_kh}}-{{$teacher->name_en}}" class="form-control" id="lable_name" placeholder="នាមត្រកូល នាមខ្លួន - FirstName LastName">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_gender" class="col-sm-3 col-form-label">{{trans('controls.teachers.gender')}}</label>
                    <div class="col-sm-9">
                        <select class="custom-select" name="gender">
                            <option>{{trans('controls.forms.Please Select')}}</option>
                            <option {{$teacher->gender=='m'?'selected':''}} value="m">{{trans('controls.forms.Male')}}</option>
                            <option {{$teacher->gender=='f'?'selected':''}} value="f">{{trans('controls.forms.Female')}}</option>
                          </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_dob" class="col-sm-3 col-form-label">{{trans('controls.teachers.dob')}}</label>
                    <div class="col-sm-9">
                        <div class="input-group date" id="lable_dob" data-target-input="nearest">
                            <input type="date" name="teacher_dob" value="{{$teacher->dob}}" id="lable_dob" class="form-control">
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_pob" class="col-sm-3 col-form-label">{{trans('controls.teachers.pob')}}</label>
                    <div class="col-sm-9">
                        <input type="text" name="teacher_pob" value="{{$teacher->pob}}" class="form-control" id="lable_pob" placeholder="គោករុន មុខប៉ែន ពួក សៀមរាប">
                    </div>
                </div>

                 <div class="form-group row">
                    <label for="lable_t_address" class="col-sm-3 col-form-label">{{trans('controls.teachers.address')}}</label>
                    <div class="col-sm-9">
                        <input type="text"  name="teacher_address" value="{{$teacher->address}}" class="form-control" id="lable_t_address" placeholder="គោករុន មុខប៉ែន ពួក សៀមរាប">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_t_city" class="col-sm-3 col-form-label">{{trans('controls.schools.city')}}</label>
                    <div class="col-sm-9">
                        <input type="text" name="teacher_city" value="{{$teacher->city}}" class="form-control" id="lable_t_city" placeholder="សៀមរាប">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_t_email" class="col-sm-3 col-form-label">{{trans('controls.schools.email')}}</label>
                    <div class="col-sm-9">
                        <input type="text" name="teacher_email" value="{{$user->email}}" class="form-control" id="lable_t_email" placeholder="teacher_name@gmail.com">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_t_profile" class="col-sm-3 col-form-label">{{trans('controls.teachers.profile')}}</label>
                    <div class="col-sm-9">
                        <div class="custom-file">
                            <input type="file">
                        </div>
                    </div>
                </div>

            </div>

        </div>



    </form>
</div>

resources/views/backend/class_result_report/modal/show.blade.php
<div class="container pt-1">
    {{-- <form action="{{ route('schools.update',$school) }}" method="post"> --}}
    <form>
        {{-- @csrf
        {{ method_field('PUT') }} --}}

        <div class="row">
            <div class="col-md-6 bg-info pt-3">

                  <div class="form-group row">
                        <label for="lable_s_name" class="col-sm-3 col-form-label">{{trans('controls.schools.name')}}</label>
                        <div class="col-sm-9">
                            <label class="form-control">{{$school->name}}</label>
                        </div>
                    </div>


                    <div class="form-group row">
                        <label for="lable_s_phone" class="col-sm-3 col-form-label">{{trans('controls.schools.phone')}}</label>
                        <div class="col-sm-9">
                            <label class="form-control">{{$school->phone}}</label>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="lable_s_email" class="col-sm-3 col-form-label">{{trans('controls.schools.email')}}</label>
                        <div class="col-sm-9">
                            <label class="form-control">{{$school->email}}</label>

                            {{-- <input type="email" name="school_email" value="{{$school->email}}" class="form-control" id="lable_s_email" placeholder="yourschool@gmail.com"> --}}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="lable_s_city" class="col-sm-3 col-form-label">{{trans('controls.schools.city')}}</label>
                        <div class="col-sm-9">
                            <label class="form-control">{{$school->city}}</label>

                            {{-- <input type="text" name="school_city" value="{{$school->city}}" class="form-control" id="lable_s_city" placeholder="Siem Reap"> --}}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="lable_s_address" class="col-sm-3 col-form-label">{{trans('controls.schools.address')}}</label>
                        <div class="col-sm-9">
                            <label class="form-control">{{$school->address}}</label>

                            {{-- <input type="text" name="school_address" value="{{$school->address}}"  class="form-control" id="lable_s_address" placeholder="ភូមិ ឃុំ ស្រុក"> --}}
                        </div>
                    </div>



            </div>


            <div class="col-md-6 bg-success pt-3">
                {{-- Director --}}
                <div class="form-group row">
                    <label for="lable_name" class="col-sm-3 col-form-label">{{trans('controls.schools.director_name')}}</label>
                    <div class="col-sm-9">
                        <label class="form-control">{{$teacher->name_kh}}-{{$teacher->name_en}}</label>

                        {{-- <input type="text" name="teacher_name" value="{{$teacher->name_kh}}-{{$teacher->name_en}}" class="form-control" id="lable_name" placeholder="នាមត្រកូល នាមខ្លួន - FirstName LastName"> --}}
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_gender" class="col-sm-3 col-form-label">{{trans('controls.teachers.gender')}}</label>
                    <div class="col-sm-9">
                        <label class="form-control">{{$teacher->gender=='m'?trans('controls.forms.Male'):trans('controls.forms.Female')}}</label>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_dob" class="col-sm-3 col-form-label">{{trans('controls.teachers.dob')}}</label>
                    <div class="col-sm-9">
                        <div class="input-group date" id="lable_dob" data-target-input="nearest">
                            {{-- <input type="date" name="teacher_dob" value="{{$teacher->dob}}" id="lable_dob" class="form-control"> --}}
                            <label class="form-control">{{$teacher->dob}}</label>

                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_pob" class="col-sm-3 col-form-label">{{trans('controls.teachers.pob')}}</label>
                    <div class="col-sm-9">
                            <label class="form-control">{{$teacher->pob}}</label>
                    </div>
                </div>

                 <div class="form-group row">
                    <label for="lable_t_address" class="col-sm-3 col-form-label">{{trans('controls.teachers.address')}}</label>
                    <div class="col-sm-9">
                        {{-- <input type="text"  name="teacher_address" value="{{$teacher->address}}" class="form-control" id="lable_t_address" placeholder="គោករុន មុខប៉ែន ពួក សៀមរាប"> --}}
                        <label class="form-control">{{$teacher->address}}</label>

                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_t_city" class="col-sm-3 col-form-label">{{trans('controls.schools.city')}}</label>
                    <div class="col-sm-9">
                        <label class="form-control">{{$teacher->city}}</label>

                        {{-- <input type="text" name="teacher_city" value="{{$teacher->city}}" class="form-control" id="lable_t_city" placeholder="សៀមរាប"> --}}
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_t_email" class="col-sm-3 col-form-label">{{trans('controls.schools.email')}}</label>
                    <div class="col-sm-9">
                        <label class="form-control">{{$user->email}}</label>

                        {{-- <input type="text" name="teacher_email" value="{{$user->email}}" class="form-control" id="lable_t_email" placeholder="teacher_name@gmail.com"> --}}
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lable_t_profile" class="col-sm-3 col-form-label">{{trans('controls.teachers.profile')}}</label>
                    <div class="col-sm-9">
                        <div class="custom-file">
                            {{-- <input type="file"> --}}
                        <img style="width: 100px;" src="{{asset('images/logo.png')}}" alt="">

                        </div>
                    </div>
                </div>

            </div>

        </div>



    </form>
</div>